### ISSUE TITLE
Clarify dotpath usage in `queryables.name` 

### ISSUE THREAD

**Issue by mmcfarland** [stac-utils/pgstac#134]
pgstac ships with 3 queryable definitions, including `eo:cloud_cover` which may exist on an item `content.properties` field, but is registered without the `properties` in its path. It also accepts filter and sort attributes to be sent with or without `properties` on the path. However, when fetching a queryable record, it looks for an exact match on dotpath:

https://github.com/stac-utils/pgstac/blob/e72a17ca33e552e417a8863bdd4289f9fd4db030/sql/002a_queryables.sql#L51

In the case of `eo:cloud_cover`, users passing `properties.eo:cloud_cover` as a sortby value (as used in the [examples](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/sort#:~:text=GET%20/search%3Fsortby%3D%2D-,properties.eo%3Acloud_cover,-Note%20that%20examples)) won't match a record and the expression will get wrapped in the default `to_text`, resulting in incorrect sort results.

A couple of options:
- Should pgstac become more strict about using fully qualified paths for input attributes that always include `properties.` in things like search and sort? It's easy to find stac api spec examples that include or omit `properties`, but it's not clear if that ambivalence is intentional.
- If not, should we always register queryables with their fully qualified name and ensure they're accessed like how `queryable` generates the path for its output?
https://github.com/stac-utils/pgstac/blob/e72a17ca33e552e417a8863bdd4289f9fd4db030/sql/002a_queryables.sql#L66-L73

**Comment by bitner** [comment]
@mmcfarland The spec is definitely ambiguous here.

- For [sortby](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/sort), the spec does not specify, but the examples all include the "properties.<propname>".
- For [query](https://github.com/radiantearth/stac-api-spec/blob/master/fragments/query/README.md), again, it is not specified, but none of the examples include the properties prefix.
- For [filter](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/filter), it gets even more confusing as the first [mention](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/filter#filter-expressiveness) actually starts the path at the item level "item.properties.eo:cloud_cover". The [Queryables](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/filter#queryables) section specifies that "any syntactically-valid term for a property will be accepted" but further that "It is recommended to use fully-qualified property names (e.g., properties.eo:cloud_cover)." Immediately below that section, however, it states "Fields in Item Properties should be exposed with their un-prefixed names, and not require expressions to prefix them with properties, e.g., eo:cloud_cover instead of properties.eo:cloud_cover." All of the examples provided do *not* use the properties prefix.
- For [Fields](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/fields), properties is included as there is the ability to filter nested tree structures (ie hide anything in assets, but show anything in properties)

Given this ambiguity in the spec, I think that the least confusing for a user would be to accept either "properties.eo:cloud_cover" or "eo:cloud_cover" when used in sortby, query, or filter. In the Queryables endpoint, I think we should just return the non-prefixed "eo:cloud_cover" (and continue to index things internally in the queryables table just by the non-prefixed name). In all of these cases, something is either at the root (datetime, geometry) or it's a property. For the Fields extension, since that extension also includes links, assets, stac_version, stac_extensions, I think it is appropriate that we continue to require the full path ("properties.eo:cloud_cover") as it is very directly applying to the root of the output format rather than applying to a specific record.

If this sounds acceptable, I'll make sure to wrap all this behavior along with tests into PR #133.

**Comment by bitner** [comment]
@philvarner Do you have any $.02 on ^^^

**Comment by philvarner** [comment]
Your approach sounds good to me.

They're a bit ambiguous because there was some difference of opinion as to whether they should be fully-qualified or also allow the unqualified name. Implementations are all over the place on that. Now that we have a good pattern with /queryable, we should probably follow that for v2 of fields and sortby, but for now, it just has to be communicated to the user out of band or support either. 

I will clean up that confusing bit in Filter, since that's the only one that's clearly defined.

**Comment by mmcfarland** [comment]
All sounds good to me -- thanks!
