### ISSUE TITLE
Deleting and recreating collection causes item insert errors

### ISSUE THREAD

**Issue by ccicotta** [stac-utils/pgstac#185]
When deleting an existing collection and then recreating it, future item inserts into that collection appear to cause an error. Only creating a collection with a new name are inserts possible again.

The error encountered is `ERROR: relation "_items_118" does not exist at character 174` with the ID after `_items_` incrementing with each insert attempt.

**Comment by bitner** [comment]
Note: the fix for #185 in #188 will only prevent this in the future. If you are not able to re-create a collection with the same name, you will need to make sure that the base partition for that collection has been dropped and Delete all records for partitions with that collection from the partition_stats table.
