### ISSUE TITLE
Deadlock issue arises during STAC items ingestion

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/pgstac#211]
I've encountered a deadlock problem while trying to ingest STAC items using multiple processes. Is it intended that pgstac only supports a non-concurrent method for uploading data, or is this a bug?

```
psycopg.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 28054 waits for AccessExclusiveLock on relation 18455 of database 16399; blocked by process 28538.
Process 28538 waits for AccessExclusiveLock on relation 18455 of database 16399; blocked by process 28054.
HINT:  See server log for query details.
CONTEXT:  SQL statement "
            ALTER TABLE _items_1 DROP CONSTRAINT IF EXISTS _items_1_dt;
        "
PL/pgSQL function drop_table_constraints(text) line 33 at EXECUTE
SQL statement "SELECT drop_table_constraints(_partition_name)"
PL/pgSQL function check_partition(text,tstzrange,tstzrange) line 143 at PERFORM
```

**Comment by bitner** [comment]
@drnextgis Are you loading using the pypgstac loader or using a connected API (ie stac-fastapi.pgstac)?

PGStac supports concurrent loading, but there are instances that if the transactions for the part of the loading process that manages the partitions used by pgstac overlaps another instance that is trying to modify the same partition that a deadlock can occur. When using either the items_staging tables or the pgstac crud functions the entire process of checking/creating partitions and constraints is done within the same transaction as the data loading, so the time the transaction is open can be a considerable amount of time leading to more likelihood that this will happen.

Pypgstac splits loads by collection/month as well as into chunks of no more than 10,000 items in a single transaction and does the partition management in a separate transaction to reduce the likelihood of locking situations (at the cost of the ability to fully rollback a load). It is still possible, however.

**Comment by drnextgis** [comment]
Thank you @bitner for a prompt reply! Yes we are using the pypgstac loader:

```
from pypgstac.db import PgstacDB
from pypgstac.load import Loader

db_loader = Loader(db=PgstacDB(dsn=f"postgresql://..."))
db_loader.load_items(
    file="chunk_01.njson",
    insert_mode="upsert",
    dehydrated=False,
    chunksize=10000,
)
```

Based on what you mentioned, it seems that the method we use for ungesting data into the pgstac database is highly susceptible to deadlocks. We divide long captures into numerous smaller STAC items (tiles) each of which possesses the same timestamp. Subsequently, we further divide these STAC items into multiple files (such as `chunk_01.njson`, `chunk_02.njson`, ...) and ingest them concurrently.

However, even if we consolidate all STAC items into a single file, there remains a possibility of encountering deadlocks. This is because there could be a scenario where more than one scene is being ingested simultaneously.

Any suggestions on how to address this issue would be greatly appreciated.

**Comment by bitner** [comment]
I'm not entirely sure what you mean by a scene, but I believe that much of what you are trying to do is what pypgstac is doing behind the scenes anyway.

Anytime you are loading data into postgres, you are trying to strike a balance between transactional overhead and long held locks. If you load data in very small amounts at a time, each transaction has a fair amount of overhead in time and memory. If you try to load huge amounts of data at once, it means that any locks needed for any part of the operation will be held open for the entirety of the transaction leading to a higher likelihood of lock contention.

With pgstac, the overhead per transaction is even greater because we need to check and create or modify partitions and constraints for every transaction.

The most intrusive locks are caused by the need for exclusive access when accessing or modifying partitions. Pypgstac tries to be a bit smart in how it splits up data loads to mitigate this. The first thing it does is sorting the data and breaking it into chunks by what partition the data will end up in (using the collection and datetime). For each of these chunks, it will then see if the data fits into an existing partition / constraints. If not, it will either create the partition or remove the constraints in a transaction on it's own. Then it will further break that chunk down into chunks of 10000 item records committing each transaction along the way. Then it will add back any constraints in a final transaction.

If you are breaking things up by time smaller than a month, you are probably both adding transactional overhead as well as increasing the chance of locking situations when trying to split and do things concurrently. Realistically, I am not sure how much benefit trying to do things concurrently will help speed things up as the io bottlenecks will just increase (which for most hosted database deployments is going to be a large limiting factor) and you are upping the lock pressure. If you *do* try to load things concurrently, you would just want to try to limit any concurrent loading of items into **the same partition**.

**Comment by drnextgis** [comment]
@bitner the explanation is crystal clear! Thanks!
