### ISSUE TITLE
looking for consistency in search hash. 

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/pgstac#74]
It seems that every time there is a pgstac update, the `hash` for a search will be different (I have hash based test in https://github.com/stac-utils/titiler-pgstac/blob/master/tests/test_titiler_pgstac.py#L7-L8 and I have to update the hash every time pgstac version change)

I think this is usually fine, but it would be great if we could have a way to have a `consistent` id for registering/searching/accessing a search query. 

I'm mostly thinking about using a `name` to describe a search query. This would be optional, a search could still be located with it's hash, but also with it's name. 

https://github.com/stac-utils/pgstac/blob/76512ab50e1373e3f77c65843cf328cbe6dd0dec/sql/004_search.sql#L1000-L1004

**Comment by bitner** [comment]
Also -- how'd you make the link to the lines pop out in the text??

**Comment by vincentsarago** [comment]
> Also -- how'd you make the link to the lines pop out in the text??

`https://github.com/stac-utils/pgstac/blob/76512ab50e1373e3f77c65843cf328cbe6dd0dec/sql/004_search.sql#L839-L855`

**Comment by vincentsarago** [comment]
Thinking more about this, I think the current behaviour is ok.

**Comment by robintw** [comment]
I'm struggling with a similar problem here.

I have some metadata that I'm storing with the search, which is using the approach detailed in the [titiler-pgstac docs](https://stac-utils.github.io/titiler-pgstac/advanced/metadata/) to store things like pre-defined visualisations in the `defaults` key, and lists of assets you can select in the `assets` key. However, because the hash is generated based on the search _and_ the metadata, I'm finding that whenever I update the metadata (for example, to add another pre-defined visualisation), I get a new hash. As this hash is used in the URLs for tiles in titiler-pgstac, that means that any other apps that use the tiles from titiler-pgstac have to keep updating their hash.

Is there a particular reason that the metadata needs to be taken into account when calculating the hash? Would it be possible to calculate the hash just on the search information and not the metadata?
